name: Trigger

on:
  schedule:
    - cron: "0 19 * * *"
  repository_dispatch:

jobs:
  trigger:
    name: Trigger builds
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH access
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup git access to allow triggering build workflow
        run: |
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          git config --global user.email "<>"
          git config --global user.name "Automatic Build"
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Tag new cbc release if necessary
        run: |
          version=$(git ls-remote --tags https://github.com/coin-or/Cbc | fgrep releases | cut -d '/' -f 4 | sort -nr -t. -k1,1 -k2,2 -k3,3 | head -1)
          echo "Pushing tag for version $version"
          git tag -a "releases/$version" -m "Cbc version $version (stable)"
          git push origin -f "releases/$version"
      - name: Tag nightly cbc build if necessary
        run: |
          sha=$(git ls-remote https://github.com/coin-or/Cbc refs/heads/master | awk '{print $1;}')
          night=$(date +'%Y-%m-%d')          
          echo "Pushing tag for nightly $sha"
          git tag -a "nightly/$sha" -m "Cbc nightly ($night)"
          git push -f origin "nightly/$sha"
